{{ config(
    materialized='table'
) }}

WITH matches_data AS (
    SELECT * FROM {{ ref('fact_cricket_matches') }}
)

SELECT
    COUNT(MATCH_ID) AS TOTAL_MATCHES,
    COUNT_IF(RESULT_TYPE = 'Live') AS LIVE_MATCHES,
    COUNT_IF(RESULT_TYPE IN ('Completed', 'Match Tied')) AS COMPLETED_MATCHES,
    COUNT_IF(RESULT_TYPE IN ('Abandoned', 'No Result')) AS ABANDONED_MATCHES,
    COUNT(DISTINCT CITY) AS CITIES_INGESTED,
    COUNT(DISTINCT VENUE_NAME) AS VENUES_REGISTERED,
    COUNT(DISTINCT MATCHTYPE) AS MATCH_FORMATS,
    COUNT(DISTINCT RESULT_TYPE) AS RESULT_DECIDERS
FROM matches_data
